import re
from playwright.sync_api import Page, expect


def test_T01(page: Page) -> None:
    page.goto("http://127.0.0.1:8000/register/")
    page.locator("#id_name").click()
    page.locator("#id_name").fill("vanshikas2018@gmail.com")
    page.locator("#id_username").click()
    page.locator("#id_username").fill("Vanshik@8")
    page.locator("#id_name").click()
    page.locator("#id_name").press("Control+c")
    page.locator("#id_name").press("Control+a")
    page.locator("#id_name").press("Control+x")
    page.get_by_role("main").locator("form div").filter(has_text="Email").click()
    page.locator("#id_email").fill("vanshikas2018@gmail.com")
    page.locator("#id_name").click()
    page.locator("#id_name").fill("Vanshika Singh")
    page.locator("#id_password1").click()
    page.locator("#id_password1").fill("cursedchild")
    page.locator("#id_password1").press("Control+a")
    page.locator("#id_password1").fill("radhikaraina560")
    page.locator("#id_password2").click()
    page.locator("#id_password2").fill("radhikaraina560")
    page.locator("#id_password2").press("Enter")
    page.get_by_role("button", name="chevron-down").click()
    page.get_by_role("link", name="sign-out Logout").click()
    page.get_by_role("link", name="Login").click()
    page.get_by_role("link", name="Sign Up").click()
    page.locator("#id_name").click()
    page.locator("#id_name").fill("Vanshika SIngh")
    page.locator("#id_username").click()
    page.locator("#id_username").fill("vanshika")
    page.locator("#id_email").click()
    page.locator("#id_email").fill("vanshika734093$kjfgmailcom")
    page.locator("#id_password1").click()
    page.locator("#id_password1").fill("hsfvhdaskgfdslg")
    page.locator("#id_password2").click()
    page.locator("#id_password2").click()
    page.locator("#id_password2").fill("hsfvhdaskgfdslg")
    page.locator("#id_password2").press("Enter")
    page.get_by_text("Password", exact=True).click()
